---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/info
  label: Info
  create: all
  match: "**/*"
  templates:
  - info
- type: directory
  path: content/careers
  label: Careers
  create: documents
  match: "**/*"
  templates:
  - careers
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Home Page
- type: directory
  path: content/showcase
  label: Showcase
  create: all
  match: "**/*"
  templates:
  - showcase
- type: document
  path: data/carousel.json
  label: Carousel
- type: document
  path: data/homevideo.json
  label: Video
- type: directory
  path: content/reviews
  label: Reviews
  create: documents
  match: "**/*"
  templates:
  - review
upload_dir: static/imgs
public_path: "/imgs"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.6
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
